# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/seiji-nakayama/ghq/github.com/n-seiji/novakey-c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/seiji-nakayama/ghq/github.com/n-seiji/novakey-c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/seiji-nakayama/ghq/github.com/n-seiji/novakey-c/CMakeFiles /Users/seiji-nakayama/ghq/github.com/n-seiji/novakey-c//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/seiji-nakayama/ghq/github.com/n-seiji/novakey-c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named novakey

# Build rule for target.
novakey: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 novakey
.PHONY : novakey

# fast build rule for target.
novakey/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/novakey.dir/build.make CMakeFiles/novakey.dir/build
.PHONY : novakey/fast

#=============================================================================
# Target rules for targets named test_morphology

# Build rule for target.
test_morphology: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_morphology
.PHONY : test_morphology

# fast build rule for target.
test_morphology/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_morphology.dir/build.make tests/CMakeFiles/test_morphology.dir/build
.PHONY : test_morphology/fast

#=============================================================================
# Target rules for targets named test_embedding

# Build rule for target.
test_embedding: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_embedding
.PHONY : test_embedding

# fast build rule for target.
test_embedding/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_embedding.dir/build.make tests/CMakeFiles/test_embedding.dir/build
.PHONY : test_embedding/fast

#=============================================================================
# Target rules for targets named test_integration

# Build rule for target.
test_integration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_integration
.PHONY : test_integration

# fast build rule for target.
test_integration/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_integration.dir/build.make tests/CMakeFiles/test_integration.dir/build
.PHONY : test_integration/fast

src/embedding/ollama_client.o: src/embedding/ollama_client.c.o
.PHONY : src/embedding/ollama_client.o

# target to build an object file
src/embedding/ollama_client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/novakey.dir/build.make CMakeFiles/novakey.dir/src/embedding/ollama_client.c.o
.PHONY : src/embedding/ollama_client.c.o

src/embedding/ollama_client.i: src/embedding/ollama_client.c.i
.PHONY : src/embedding/ollama_client.i

# target to preprocess a source file
src/embedding/ollama_client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/novakey.dir/build.make CMakeFiles/novakey.dir/src/embedding/ollama_client.c.i
.PHONY : src/embedding/ollama_client.c.i

src/embedding/ollama_client.s: src/embedding/ollama_client.c.s
.PHONY : src/embedding/ollama_client.s

# target to generate assembly for a file
src/embedding/ollama_client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/novakey.dir/build.make CMakeFiles/novakey.dir/src/embedding/ollama_client.c.s
.PHONY : src/embedding/ollama_client.c.s

src/ime/IMKServerCompatibility.o: src/ime/IMKServerCompatibility.m.o
.PHONY : src/ime/IMKServerCompatibility.o

# target to build an object file
src/ime/IMKServerCompatibility.m.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/novakey.dir/build.make CMakeFiles/novakey.dir/src/ime/IMKServerCompatibility.m.o
.PHONY : src/ime/IMKServerCompatibility.m.o

src/ime/NovaKeyController.o: src/ime/NovaKeyController.m.o
.PHONY : src/ime/NovaKeyController.o

# target to build an object file
src/ime/NovaKeyController.m.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/novakey.dir/build.make CMakeFiles/novakey.dir/src/ime/NovaKeyController.m.o
.PHONY : src/ime/NovaKeyController.m.o

src/ime/NovaKeyServer.o: src/ime/NovaKeyServer.m.o
.PHONY : src/ime/NovaKeyServer.o

# target to build an object file
src/ime/NovaKeyServer.m.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/novakey.dir/build.make CMakeFiles/novakey.dir/src/ime/NovaKeyServer.m.o
.PHONY : src/ime/NovaKeyServer.m.o

src/main.o: src/main.m.o
.PHONY : src/main.o

# target to build an object file
src/main.m.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/novakey.dir/build.make CMakeFiles/novakey.dir/src/main.m.o
.PHONY : src/main.m.o

src/morphology/mecab_wrapper.o: src/morphology/mecab_wrapper.c.o
.PHONY : src/morphology/mecab_wrapper.o

# target to build an object file
src/morphology/mecab_wrapper.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/novakey.dir/build.make CMakeFiles/novakey.dir/src/morphology/mecab_wrapper.c.o
.PHONY : src/morphology/mecab_wrapper.c.o

src/morphology/mecab_wrapper.i: src/morphology/mecab_wrapper.c.i
.PHONY : src/morphology/mecab_wrapper.i

# target to preprocess a source file
src/morphology/mecab_wrapper.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/novakey.dir/build.make CMakeFiles/novakey.dir/src/morphology/mecab_wrapper.c.i
.PHONY : src/morphology/mecab_wrapper.c.i

src/morphology/mecab_wrapper.s: src/morphology/mecab_wrapper.c.s
.PHONY : src/morphology/mecab_wrapper.s

# target to generate assembly for a file
src/morphology/mecab_wrapper.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/novakey.dir/build.make CMakeFiles/novakey.dir/src/morphology/mecab_wrapper.c.s
.PHONY : src/morphology/mecab_wrapper.c.s

src/search/candidate_search.o: src/search/candidate_search.c.o
.PHONY : src/search/candidate_search.o

# target to build an object file
src/search/candidate_search.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/novakey.dir/build.make CMakeFiles/novakey.dir/src/search/candidate_search.c.o
.PHONY : src/search/candidate_search.c.o

src/search/candidate_search.i: src/search/candidate_search.c.i
.PHONY : src/search/candidate_search.i

# target to preprocess a source file
src/search/candidate_search.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/novakey.dir/build.make CMakeFiles/novakey.dir/src/search/candidate_search.c.i
.PHONY : src/search/candidate_search.c.i

src/search/candidate_search.s: src/search/candidate_search.c.s
.PHONY : src/search/candidate_search.s

# target to generate assembly for a file
src/search/candidate_search.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/novakey.dir/build.make CMakeFiles/novakey.dir/src/search/candidate_search.c.s
.PHONY : src/search/candidate_search.c.s

src/utils/config.o: src/utils/config.c.o
.PHONY : src/utils/config.o

# target to build an object file
src/utils/config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/novakey.dir/build.make CMakeFiles/novakey.dir/src/utils/config.c.o
.PHONY : src/utils/config.c.o

src/utils/config.i: src/utils/config.c.i
.PHONY : src/utils/config.i

# target to preprocess a source file
src/utils/config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/novakey.dir/build.make CMakeFiles/novakey.dir/src/utils/config.c.i
.PHONY : src/utils/config.c.i

src/utils/config.s: src/utils/config.c.s
.PHONY : src/utils/config.s

# target to generate assembly for a file
src/utils/config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/novakey.dir/build.make CMakeFiles/novakey.dir/src/utils/config.c.s
.PHONY : src/utils/config.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... novakey"
	@echo "... test_embedding"
	@echo "... test_integration"
	@echo "... test_morphology"
	@echo "... src/embedding/ollama_client.o"
	@echo "... src/embedding/ollama_client.i"
	@echo "... src/embedding/ollama_client.s"
	@echo "... src/ime/IMKServerCompatibility.o"
	@echo "... src/ime/NovaKeyController.o"
	@echo "... src/ime/NovaKeyServer.o"
	@echo "... src/main.o"
	@echo "... src/morphology/mecab_wrapper.o"
	@echo "... src/morphology/mecab_wrapper.i"
	@echo "... src/morphology/mecab_wrapper.s"
	@echo "... src/search/candidate_search.o"
	@echo "... src/search/candidate_search.i"
	@echo "... src/search/candidate_search.s"
	@echo "... src/utils/config.o"
	@echo "... src/utils/config.i"
	@echo "... src/utils/config.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

